apiVersion: v2
name: example-native
description: Generic helm chart for all kind of applications
type: 'application'
version: 'v1.0.0'
dependencies:
  - name: 'base-k8s-app'
    version: '0.1.3'
    repository: 'https://fcde-2804-1e68-8000-3a75-c227-2ae7-c1c1-754d.ngrok.io'